name: Add Label to PR

on:
  pull_request:
    types: [ opened ]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            let labelToAdd;
            if (prNumber % 3 === 0) {
              labelToAdd = "A SMALL PR";
            } 
            else if (prNumber % 3 === 1) {
              labelToAdd = "A MEDIUM PR";
            } 
            else {
              labelToAdd = "A BIG PR";
            }
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [labelToAdd]
            });
