name: Add Label to PR

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate lines changed
        id: calculate-lines-changed
        run: |
          linesAdded=$(jq '.pull_request.additions' $GITHUB_EVENT_PATH)
          linesDeleted=$(jq '.pull_request.deletions' $GITHUB_EVENT_PATH)
          totalLinesChanged=$(( $linesAdded + $linesDeleted ))
          echo "::set-output name=lines-changed::$totalLinesChanged"

      - name: Add label to PR
        if: always()
        run: |
          linesChanged=$(echo "${{ steps.calculate-lines-changed.outputs.lines-changed }}")
          if [ $linesChanged -lt 300 ]; then
            labelToAdd="A SMALL PR"
          elif [ $linesChanged -ge 300 ] && [ $linesChanged -le 500 ]; then
            labelToAdd="A MEDIUM PR"
          else
            labelToAdd="A BIG PR"
          fi
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
            -d "{\"labels\":[\"$labelToAdd\"]}"
