name: Add Size Label to PR

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate lines changed
        id: calculate-lines-changed
        run: |
          linesAdded=$(jq '.pull_request.additions' $GITHUB_EVENT_PATH)
          linesDeleted=$(jq '.pull_request.deletions' $GITHUB_EVENT_PATH)
          totalLinesChanged=$(( $linesAdded + $linesDeleted ))
          echo "lines-changed=${totalLinesChanged}" >> $GITHUB_OUTPUT

      - name: Check if label already exists
        id: check-label
        run: |
          labelToAdd=$(echo "${{ steps.calculate-lines-changed.outputs.lines-changed }}" | awk '{print ($1 < 300) ? "A SMALL PR" : ($1 >= 300 && $1 <= 500) ? "A MEDIUM PR" : "A BIG PR"}')
          existingLabels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels | jq -r '.[].name')
          echo "label-to-add=${labelToAdd}" >> $GITHUB_OUTPUT
          echo "existing-labels=${existingLabels}" >> $GITHUB_OUTPUT

      - name: Remove existing labels and add label
        if: always()
        run: |
          labelToAdd="${{ steps.check-label.outputs.label-to-add }}"
          existingLabels="${{ steps.check-label.outputs.existing-labels }}"
          if [[ $existingLabels =~ $labelToAdd ]]; then
            # Label already exists, remove other two labels
            otherLabels=$(echo "A SMALL PR,A MEDIUM PR,A BIG PR" | sed "s/$labelToAdd//g" | tr ',' '\n')
            for otherLabel in $otherLabels; do
              curl -X DELETE \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/${otherLabel}
            done
          else
            # Label doesn't exist, add label and remove other two labels
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
              -d "{\"labels\":[\"$labelToAdd\"]}"

            otherLabels="A SMALL PR,A MEDIUM PR,A BIG PR"
            for otherLabel in $otherLabels; do
              if [ "$otherLabel" != "$labelToAdd" ]; then
                curl -X DELETE \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/${otherLabel}"
              fi
            done
          fi