name: Auto Size Label to PR

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  add-label:
    runs-on: ubuntu-latest
    env:
      SMALL_PR_LABEL: "A-SMALL-PR"
      MEDIUM_PR_LABEL: "A-MEDIUM-PR"
      BIG_PR_LABEL: "A-BIG-PR"
      SMALL_THRESHOLD: 300
      MEDIUM_THRESHOLD: 500
    steps:
      - name: Calculate lines changed
        id: calculate-lines-changed
        run: |
          linesAdded=$(jq '.pull_request.additions' $GITHUB_EVENT_PATH)
          linesDeleted=$(jq '.pull_request.deletions' $GITHUB_EVENT_PATH)
          totalLinesChanged=$((linesAdded + linesDeleted))
          echo "lines-changed=${totalLinesChanged}" >>$GITHUB_OUTPUT

      - name: Check if label already exists
        id: check-label
        run: |
          linesChanged=${{ steps.calculate-lines-changed.outputs.lines-changed }}
          labelToAdd=""
          if [ $linesChanged -lt $SMALL_THRESHOLD ]; then
            labelToAdd=$SMALL_PR_LABEL
          elif [ $linesChanged -ge $SMALL_THRESHOLD ] && [ $linesChanged -le $MEDIUM_THRESHOLD ]; then
            labelToAdd=$MEDIUM_PR_LABEL
          else
            labelToAdd=$BIG_PR_LABEL
          fi
          echo "label-to-add=${labelToAdd}" >>$GITHUB_OUTPUT
          existingLabels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels | jq -r '.[].name')
          echo "existing-labels=${existingLabels}" >>$GITHUB_ENV

      - name: Remove existing labels and add label
        if: always()
        run: |
          labelToAdd="${{ steps.check-label.outputs.label-to-add }}"
          otherLabels="$SMALL_PR_LABEL $MEDIUM_PR_LABEL $BIG_PR_LABEL"
          for otherLabel in $otherLabels; do
            if [[ "$existingLabels" == *"$otherLabel"* ]]; then
              curl -X DELETE \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/${otherLabel}"
            fi
          done

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
            -d "{\"labels\":[\"${labelToAdd}\"]}"
