name: Check Passed Tests

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-when-needs-testing:
    if: !contains(github.event.pull_request.labels.*.name, 'passed-all-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR didn't passed all tests
        run: |
          echo "This PR needs testing."
          exit 1