name: Check Draft

on:
  pull_request:
    #    branches:
    #      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-draft:
    if: contains(github.event.pull_request.labels.*.name, 'needs-robot-testing')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR needs testing
        run: |
          echo "This PR needs testing."
          exit 1