name: Check Labels For PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
  push:

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: pr-number
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REF}" | jq -r '.[0].number')
          echo "pr-number=${PR_NUMBER}" >> $GITHUB_OUTPUT


      - name: Get labels for PR
        id: labels
        if: steps.pr-number.outputs.pr-number != 'null'
        run: |
          PR_NUMBER="${{ steps.pr-number.outputs.pr-number }}"
          LABELS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels" | jq -r '.[].name' | tr '\n' ',')
          IFS=',' read -r -a labels_array <<< "${LABELS}"
          echo "LABELS_ARRAY=${labels_array[*]}" >> $GITHUB_ENV

      - name: check passed-all-tests label
        run: |
          if [[ -n "$LABELS_ARRAY" ]]; then
            target_on_label="passed-all-tests"
            target_off_label="waiting-for-another-pr"
            IFS=',' read -r -a labels_array <<< "$LABELS_ARRAY"
          
            if [[ " ${labels_array[*]} " =~ " ${target_on_label} " && ! " ${labels_array[*]} " =~ " ${target_off_label} " ]]; then
              echo "Label '${target_on_label}' exists."
              echo "Label '${target_off_label}' doesn't exists."
              exit 0
            else
              echo "Label '${target_label}' does not exist or Label '${target_off_label}' doesn't exists."
              exit 1
            fi
          else
            echo "No labels found for the pull request."
            exit 1
          fi
      
