name: Get Labels for Pull Request

on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  get-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: pr-number
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REF}" | jq -r '.[0].number')
          echo "pr-number=${PR_NUMBER}" >> $GITHUB_OUTPUT


      - name: Get labels for PR
        id: labels
        if: steps.pr-number.outputs.pr-number != 'null'
        run: |
          PR_NUMBER="${{ steps.pr-number.outputs.pr-number }}"
          LABELS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels" | jq -r '.[].name')
          echo "${LABELS}"
          if [[ -n "${LABELS}" ]]; then
            echo "Labels for the pull request:"
            IFS=' ' read -r -a labels_array <<< "${LABELS}"
            for label in "${labels_array[@]}"; do
              echo "$label"
            done
          else
            echo "No labels found for the pull request."
          fi
          echo "labels=${ENCODED_LABELS}" >> $GITHUB_OUTPUT

      - name: Output labels
        run: |
          if [[ -f "$GITHUB_OUTPUT" ]]; then
            ENCODED_LABELS=$(cat "$GITHUB_OUTPUT" | grep '^labels=' | sed 's/labels=//')
            if [[ -n "$ENCODED_LABELS" ]]; then
              DECODED_LABELS=$(echo "$ENCODED_LABELS" | base64 -d)
              if [[ -n "$DECODED_LABELS" ]]; then
                echo "Labels for the pull request:"
                echo "$DECODED_LABELS"  # Output decoded labels
              else
                echo "Failed to decode labels."
              fi
            else
              echo "No labels found in $GITHUB_OUTPUT."
            fi
          else
            echo "$GITHUB_OUTPUT not found."
          fi
