name: Passed All Tests

on:
  pull_request:
    types: [ opened, labeled, unlabeled ]
  push:

jobs:
  check-label:
    runs-on: ubuntu-latest
    outputs:
      passed-tests: ${{ steps.check-label.outputs.passed-tests }}
    steps:
      - name: Check if label exists
        id: check-label
        run: |
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          if [[ "$labels" == *"passed-all-tests"* ]]; then
            echo "Label 'passed-all-tests' found on pull request."
            echo "::set-output name=passed-tests::true"
          else
            echo "Label 'passed-all-tests' not found on pull request."
            echo "::set-output name=passed-tests::false"
          fi

  fail-if-needs-testing:
    runs-on: ubuntu-latest
    needs: check-label
    steps:
      - name: Fail if PR needs testing
        if: ${{ needs.check-label.outputs.passed-tests != 'true' }}
        run: |
          echo "This PR is currently a draft."
          exit 1
