name: Check Labels For PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
  push:

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: pr-number
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REF}" | jq -r '.[0].number')
          echo "pr-number=${PR_NUMBER}" >> $GITHUB_OUTPUT


      - name: Get labels for PR
        id: labels
        if: steps.pr-number.outputs.pr-number != 'null'
        run: |
          PR_NUMBER="${{ steps.pr-number.outputs.pr-number }}"
          LABELS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels" | jq -r '.[].name' | tr '\n' ' ')
          echo "LABELS_ARRAY=${LABELS}" >> $GITHUB_ENV
          #          IFS=',' read -r -a labels_array <<< "${LABELS}"
      #          echo "LABELS_ARRAY=${labels_array[*]}" >> $GITHUB_ENV

      - name: check if there are labels
        run: |
          if [[ ! "-n ${LABELS_ARRAY}" ]]; then
            echo "no labels on this pr"
            exit 1
          else
            echo "there are this labels on this pr -> ${LABELS_ARRAY}"
          fi

      - name: check passed-all-tests label
        run: |
          target_label="passed-all-tests"
          
          if [[ " ${LABELS_ARRAY[*]} " =~ " ${target_label} " ]]; then
             echo "Label '${target_label}' exists."
          else
            echo "Label '${target_label}' does not exist."
            exit 1
          fi

      - name: check waiting-for-another-pr label
        run: |
          target_off_label="waiting-for-another-pr"
          
          if [[ ! " ${LABELS_ARRAY[*]} " =~ " ${target_off_label} " ]]; then
            echo "Label '${target_off_label}' doesn't exists."
          else
            echo "Label '${target_off_label}' exists."
            exit 1
          fi
      
